config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to:  "magemes#index"

  resources :magemes do
    member do
      put "like", to: "magemes#upvote"
    end
  end

end

app/models/mageme.rb
class Mageme < ActiveRecord::Base
	acts_as_votable
	belongs_to :user

	has_attached_file :image, styles: { medium: "300x300>" }
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :mageme
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/magemes_controller.rb
class MagemesController < ApplicationController
	before_action :find_mageme, only: [:show, :edit, :update, :destroy, :upvote]
	before_action :authenticate_user!, except: [:index, :show]


	def index
		@magemes = Mageme.all.order("created_at DESC")
	end

	def show

	end

	def new
		@mageme = current_user.mageme.build
	end

	def create
		@mageme = current_user.mageme.build(mageme_params)

		if(@mageme.save)
			redirect_to(@mageme, notice: "Successfully created new Mageme")
		else
			render 'new'
		end
	end

	def edit

	end

	def update
		if(@mageme.update(mageme_params))
			redirect_to(@mageme, notice: "Mageme updated")
		else
			render 'edit'
		end
	end

	def destroy
		@mageme.destroy
		redirect_to(root_path)
	end

	def upvote
		@mageme.upvote_by(current_user)
		redirect_to(:back)
	end

	private

	def mageme_params
		params.require(:mageme).permit(:title, :description, :image)
	end

	def find_mageme
		@mageme = Mageme.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/magemes_helper.rb
module MagemesHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
%head
	%title Image Me
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true 
	= javascript_include_tag 'application', 'data-turbolinks-track' => true 
	= csrf_meta_tags
%body
	
	%nav.navbar.navbar-default
		.container
			.navbar-brand
				%span.logo.glyphicon.glyphicon-eye-open
				= link_to "Mageme cool", root_path
				
			- if user_signed_in?
				%ul.nav.navbar-nav.navbar-right
					%li= link_to "New Mageme", new_mageme_path
					%li= link_to "Account", edit_user_registration_path
					%li= link_to "Sign Out", destroy_user_session_path, method: :delete
			- else
				%ul.nav.navbar-nav.navbar-right
					%li= link_to "Sign Up", new_user_registration_path
					%li= link_to "Sign In", new_user_session_path

	.container
		- flash.each do |name, msg|
			= content_tag :div, msg, class: "alert alert-info"
		= yield

app/views/magemes/_form.html.haml
= simple_form_for @mageme, html: { multipart: true } do |f|
	- if @mageme.errors.any?
		#errors
			%h2
			= pluralize(@magem.errors.count, 'error')
			prevented this Mageme from Saving
			%ul
				- @mageme.errors.full_messages.each do |msg|
					%li= msg
					
	.form-group
		= f.input :image, input_html: { class: 'form-control' }

	.form-group
		= f.input :title, input_html: { class: 'form-control' }

	.form-group
		= f.input :description, input_html: { class: 'form-control' }

	= f.button :submit, class: "btn btn-primary"

app/views/magemes/edit.html.haml
.col-md-6.col-md-offset-3
	.row
		.panel.panel-default
			.panel-heading
				%h1 Edit Mageme
			.panel-body
				.col-md-6.col-md-offset-3
					%strong.center Current Image
					%br/
					= image_tag @mageme.image.url('medium')

				= render 'form'

			.panel-footer
				= link_to "Cancel", mageme_path

app/views/magemes/index.html.haml
#magemes.transitions-enabled
	- @magemes.each do |mageme|
		.box.panel.panel-default
			= link_to (image_tag mageme.image.url), mageme
			.penel-body
				%h2= link_to mageme.title, mageme 
				%p.user
				Submitted By
				= mageme.user.email

app/views/magemes/new.html.haml
.col-md-6.col-md-offset-3
	.row
		.panel.panel-default
			.panel-heading
				%h1 New Form
			.panel-body
				= render 'form'
				= link_to "Back", root_path

app/views/magemes/show.html.haml
#mageme_show.row
	.col-md-8.col-md-offset-2
		.panel.panel-default
			.panel-heading.mageme_image
				= image_tag @mageme.image.url
			.panel-body
				%h1= @mageme.title
				%p.description= @mageme.description
				%p
				Submitted by
				= @mageme.user.email

			.panel-footer
				.row
					.col-md-6
						%p.user
						Submiteed by
						= @mageme.user.email
					.col-md-6
						.btn-group.pull-right
							= link_to like_mageme_path(@mageme), method: :put, class: "btn btn-default" do
								%span.glyphicon.glyphicon-heart
								= @mageme.get_upvotes.size
							- if(user_signed_in? and current_user.email == @mageme.user.email)
								= link_to "Edit", edit_mageme_path, class: "btn btn-default"
								= link_to "Delete", mageme_path, method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-default"